name = "miami-nights-board-api"
main = "src/index.js"
compatibility_date = "2026-09-06"

[[d1_databases]]
binding = "DB"
database_name = "orbit_board"
database_id = "9153a9b9-c8a2-49be-b3ce-556913f37d3f"
